timeline
    title Act I, from the Redstone sale to the FCC vote
    section Sale process, 2023 to Aug 2024
        May 2023 : Dividend cut : NAI takes $125m of rescue capital
        Jan 2024 : Special committee formed : Skydance proposal
        Apr to May 2024 : Bakish ousted : Skydance exclusivity lapses
        Jun 11 2024 : Redstone ends talks
        Jul 7 2024 : Deal signed
        Aug 2024 : Antitrust clears : Go-shop ends
    section Routine review, Aug to Nov 2024
        Aug 29 2024 : FCC applications filed
        Oct 2024 : News-distortion complaint : Trump sues CBS
        Nov 2024 : Election : FCC pleading cycle reset
    section Political review, Nov 2024 to Jul 2025
        Jan to Feb 2025 : Carr takes over FCC : Complaint reinstated : Raw transcript released
        Apr to May 2025 : Mediation begins : 60 Minutes and CBS News chiefs quit
        Jul 1 2025 : Paramount settles for $16m
        Jul 22 2025 : Skydance pledges to Carr
        Jul 24 2025 : FCC approves 2-1
    section Close
        Aug 7 2025 : Paramount Skydance starts trading
